[lib]
proc-macro = true

[package]
name = "tealr_derive"
version = "0.1.0"
authors = ["lenscas <lenscas@gmail.com>"]
edition = "2018"
repository = "https://github.com/lenscas/tealr/"

[dependencies]
syn = "1"
quote = "1"
