[package]
name = "tealr"
version = "0.0.1"
authors = ["Casper <lenscas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlua="*"